export const Commands = {
    CMD_READY: "CMD_READY",
    CMD_DARK_MODE: "CMD_DARK_MODE",
    CMD_FIRST_RUN: "CMD_FIRST_RUN",

    CMD_HTTP_GET_LOAD_APPS: "CMD_HTTP_GET_LOAD_APPS",
    CMD_HTTP_GET_APP_STORE_VERSIONS: "CMD_HTTP_GET_APP_STORE_VERSIONS",
    CMD_HTTP_GET_APP_STORE_VERSION_LOCALIZATIONS: "CMD_HTTP_GET_APP_STORE_VERSION_LOCALIZATIONS",

    CMD_HTTP_PATCH_APP_STORE_VERSION_UPDATE: "CMD_HTTP_PATCH_APP_STORE_VERSION_UPDATE",

    CMD_HTTP_POST_APP_STORE_VERSION_CREATE: "CMD_HTTP_POST_APP_STORE_VERSION_CREATE",

    CMD_SAVE_NOTIFICATION: "CMD_SAVE_NOTIFICATION",
    CMD_GET_ALL_NOTIFICATIONS: "CMD_GET_ALL_NOTIFICATIONS",
    CMD_HTTP_POST_NOTIFICATION: "CMD_HTTP_POST_NOTIFICATION",

    CMD_LOAD_APP_CONNECT_API_CREDENTIALS: "CMD_LOAD_APP_CONNECT_API_CREDENTIALS",
    CMD_SAVE_APP_CONNECT_API_CREDENTIALS: "CMD_SAVE_APP_CONNECT_API_CREDENTIALS",

}

export const PREF_TYPE = {
    DARK_MODE: "DARK_MODE"
}
