export const Commands = {
    CMD_READY: "CMD_READY",
    CMD_DARK_MODE: "CMD_DARK_MODE",
    CMD_FIRST_RUN: "CMD_FIRST_RUN",

    CMD_HTTP_GET_LOAD_APPS: "CMD_HTTP_GET_LOAD_APPS",
    CMD_HTTP_GET_APP_STORE_VERSIONS: "CMD_HTTP_GET_APP_STORE_VERSIONS",
    CMD_HTTP_GET_APP_STORE_VERSION_LOCALIZATIONS: "CMD_HTTP_GET_APP_STORE_VERSION_LOCALIZATIONS",

    CMD_HTTP_PATCH_APP_STORE_VERSION_UPDATE: "CMD_HTTP_PATCH_APP_STORE_VERSION_UPDATE",

    CMD_HTTP_POST_APP_STORE_VERSION_CREATE: "CMD_HTTP_POST_APP_STORE_VERSION_CREATE",

    CMD_SAVE_NOTIFICATION: "CMD_SAVE_NOTIFICATION",
    CMD_GET_ALL_NOTIFICATIONS: "CMD_GET_ALL_NOTIFICATIONS",
    CMD_HTTP_POST_NOTIFICATION: "CMD_HTTP_POST_NOTIFICATION",

    CMD_LOAD_APP_CONNECT_API_CREDENTIALS: "CMD_LOAD_APP_CONNECT_API_CREDENTIALS",
    CMD_SAVE_APP_CONNECT_API_CREDENTIALS: "CMD_SAVE_APP_CONNECT_API_CREDENTIALS",

    CMD_HTTP_GET_APP_REVIEW_RESPONSE: "CMD_HTTP_GET_APP_REVIEW_RESPONSE",
    CMD_HTTP_GET_ALL_APP_STORE_REVIEWS: "CMD_HTTP_GET_ALL_APP_STORE_REVIEWS",
    CMD_HTTP_POST_APP_STORE_REVIEW_RESPONSE: "CMD_HTTP_POST_APP_STORE_REVIEW_RESPONSE",
    CMD_HTTP_GET_APP_INFO: "CMD_HTTP_GET_APP_INFO",
    CMD_HTTP_GET_APP_INFO_LOCALIZATIONS: "CMD_HTTP_GET_APP_INFO_LOCALIZATIONS",

    CMD_SAVE_SCREENSHOT: "CMD_SAVE_SCREENSHOT",
    CMD_EXPORT_SCREENSHOT: "CMD_EXPORT_SCREENSHOT",
    CMD_GET_ALL_SCREENSHOT_CONFIG: "CMD_GET_ALL_SCREENSHOT_CONFIG",

    CMD_EXPORT_APP_ICON: "CMD_EXPORT_APP_ICON",
    CMD_GET_APP_ICON: "CMD_GET_APP_ICON"
}

export const PREF_TYPE = {
    DARK_MODE: "DARK_MODE"
}
